name = "portfolio-nicol"
compatibility_date = "2024-01-01"
pages_build_output_dir = "out"

# Cloudflare KV para almacenamiento de archivos (base64)
# Nota: KV tiene l√≠mite de 25MB por valor
[[kv_namespaces]]
binding = "FILES_KV"
id = "9cd34bc4412a430ab5500ce1e2b91621"

